version: "3.7"

services:

  database:
    image: mysql:5.7  
    container_name: database 
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxx  #Don't forget to enter a passwd
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: XXXXXXXX #Change Here !!!!!
      MYSQL_PASSWORD: XXXXXXXXXXXX #Change Here !!!!!!!!!
    networks:
      - ozynet

  myapp:
    image: bookstore-api:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - ozynet

networks:
  ozynet:
  


